name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  - master
  - main
  - release/*

# Parameters that can be specified when running the pipeline
parameters:
  - name: provision
    type: boolean
    default: false
  - name: deploy
    type: boolean
    default: true
  - name: trivy
    type: boolean
    default: false
    displayName: Scan Container with Trivy
  - name: sonar
    type: boolean
    default: false
    displayName: Scan Code with SonarQube
  - name: blackduck
    type: boolean
    default: false
    displayName: Scan Code with BlackDuck
  - name: acr_cleanup
    type: boolean
    default: true
    displayName: Purge Images in Container Registry
  - name: debug_mode
    type: boolean
    default: false
    displayName: Build in Debug Mode with Assertions
  - name: EMEA_DEV
    type: boolean
    default: false
  - name: EMEA_NONPROD
    type: boolean
    default: false
  - name: EMEA_PROD
    type: boolean
    default: false

variables:
  - name: app.key
    value: way
  - name: app.name
    value: valhalla
  - name: run.provision
    value: ${{ parameters.provision }}
  - name: run.deploy
    value: ${{ parameters.deploy }}
  - name: sonar.enabled
    value: ${{ parameters.sonar }}
  - name: blackduck.enabled
    value: ${{ parameters.blackduck }}
  - name: trivy.enabled
    value: ${{ parameters.trivy }}
  - name: run.acr.cleanup
    value: ${{ parameters.acr_cleanup }}
  - name: build.debug.mode
    value: ${{ parameters.debug_mode }}

stages:
  # BUILD
  - template: pipeline/build/stage.yml
    parameters:
      name: build
      variables:
        - way.emea.shared
        #- sonarqube
        - blackduck

  # RELEASE TO DEV
  - template: pipeline/release/stage.yml
    parameters:
      name: emea_dev
      enabled: eq('${{ parameters.EMEA_DEV }}', true )
      region: emea
      environment: dev
      namespace: $(app.name)
      variables:
        - way.emea.shared
        - datadog
        - way.emea.dev
      dependencies: build

  # RELEASE TO NONPROD
  - template: pipeline/release/stage.yml
    parameters:
      name: emea_nonprod
      enabled: or( eq('${{ parameters.EMEA_NONPROD }}', true ) , eq('${{ parameters.EMEA_PROD }}', true ) )
      region: emea
      environment: nonprod
      namespace: $(app.name)
      variables:
        - way.emea.shared
        - datadog
        - way.emea.nonprod
      dependencies: emea_dev

  # RELEASE TO PROD
  - template: pipeline/release/stage.yml
    parameters:
      name: emea_prod
      enabled: eq('${{ parameters.EMEA_PROD }}', true )
      region: emea
      environment: prod
      namespace: $(app.name)
      variables:
        - way.emea.shared
        - datadog
        - way.emea.prod
      dependencies: emea_nonprod