name: Valhalla Changelog Validation
on: [pull_request]

jobs:
  build:
    name: Changelog Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate
        shell: bash
        run: |
          git fetch origin master --depth 1
          LINE_COUNT=$(git diff origin/master -- CHANGELOG.md | wc -l)
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          PR_TITLE=$(jq --raw-output .pull_request.title "$GITHUB_EVENT_PATH")
          if [ ${LINE_COUNT} -eq 0 ]; then
            printf "\x1b[31;1mNo CHANGELOG entries detected. Consider whether this PR warrents one, for example:\x1b[0m\n"
            printf "\x1b[33;1m* ${PR_TITLE} [#${PR_NUMBER}](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/pull/${PR_NUMBER})\x1b[0m\n"
            exit 1
          fi
          #TODO: validate changelog line format
